name: Generate Snake Game

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Gerar animação da cobrinha
    runs-on: ubuntu-latest

    steps:
      # Clona o repositório
      - uses: actions/checkout@v2

      # Gera a animação da cobrinha
      - uses: Platane/snk@v3
        with:
          github_user_name: pedro12u
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Publica os arquivos gerados na branch 'output'
      - name: Publicar animação
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
